import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Meshak | Frontend Developer & AI Website Builder",
  description:
    "Meshak is a Portugal-based BCA student learning HTML, CSS, JavaScript, C++, Python, React, Next.js, AI tools, and automation for modern websites.",
  keywords: [
    "Meshak",
    "BCA student",
    "Portugal frontend developer",
    "AI website builder",
    "AI automation",
    "local business websites",
    "reactjs",
    "nextjs",
    "react",
    "portfolio",
    "supabase",
    "n8n",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "python",
    "c++",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Meshak",
  },
} as const;
